branch-defaults:
  refactor/fishNote-fishKnowledge-namesapce:
    environment: Tao-among-env
environment-defaults:
  Tao-among-env:
    branch: null
    repository: null
global:
  application_name: tao-among
  default_ec2_keyname: aws-eb
  default_platform: PHP 8.3 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
